# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inicioDesktop.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.485, y1:0, x2:0.511, y2:0.982955, stop:0 rgba(251, 160, 42, 255), stop:1 rgba(250, 74, 12, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(265, 260, 521, 171))
        self.label.setMouseTracking(False)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label.setAcceptDrops(False)
        self.label.setToolTipDuration(2)
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/imgLogoPuroSabor/Group 67 (1).png);")
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.iniciarButton = QtWidgets.QPushButton(self.centralwidget)
        self.iniciarButton.setGeometry(QtCore.QRect(265, 589, 318, 83))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.iniciarButton.setFont(font)
        self.iniciarButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iniciarButton.setStyleSheet("background-color: rgb(241, 241, 241);")
        self.iniciarButton.setObjectName("iniciarButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1159, 238, 501, 451))
        self.label_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"background-image: url(:/cardapioLogin/menu.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.iniciarButton.setText(_translate("MainWindow", "Iniciar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
