# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDesktopReal3.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 394))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("headerEntrar.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 468, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.emailLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.emailLogin.setGeometry(QtCore.QRect(560, 530, 800, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.emailLogin.setFont(font)
        self.emailLogin.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-bottom-color: rgb(44, 44, 44);")
        self.emailLogin.setObjectName("emailLogin")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 620, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.senhaLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.senhaLogin.setGeometry(QtCore.QRect(560, 690, 800, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        self.senhaLogin.setFont(font)
        self.senhaLogin.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"border-bottom-color: rgb(44, 44, 44);")
        self.senhaLogin.setObjectName("senhaLogin")
        self.iniciarButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.iniciarButton_2.setGeometry(QtCore.QRect(790, 800, 318, 83))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.iniciarButton_2.setFont(font)
        self.iniciarButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.iniciarButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.485, y1:0, x2:0.511, y2:0.982955, stop:0 rgba(251, 160, 42, 255), stop:1 rgba(250, 74, 12, 255));\n"
"color: rgb(241, 241, 241);")
        self.iniciarButton_2.setObjectName("iniciarButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "E-mail"))
        self.label_3.setText(_translate("MainWindow", "Senha"))
        self.iniciarButton_2.setText(_translate("MainWindow", "Entrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
